ARG sourceimage=khulnasoft/uptrading
ARG sourcetag=develop
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-upai.txt /uptrading/

RUN pip install -r requirements-upai.txt --user --no-cache-dir
